overrides:
  - files: "*.xml"
    options:
      bracketSpacing: false
      printWidth: 88
      proseWrap: always
      semi: true
      trailingComma: "es5"
      htmlWhitespaceSensitivity: "ignore"
      parser: "html"
